project_id = "ylptmhebzazguvbevcaw"

[functions.claude-intent]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.finora-debates]
verify_jwt = false

[functions.claude-vision]
verify_jwt = false

[functions.generate-character]
verify_jwt = false
